#!/usr/bin/env python3
"""Generate a self-contained reveal.js HTML deck from slide_outline.md.

Why this exists: Chrome blocks reveal.js's runtime fetch of a local .md file
under the file:// origin, and a live CDN is a risk during a talk. This script
inlines the slides into slides.html and uses the locally bundled reveal.js in
report/slides/reveal/, so the deck opens straight from disk with no network and
no fetch. slide_outline.md remains the single source of truth; re-run this
script after editing it:

    python3 report/slides/build_slides.py

Generated by Claude Code.
"""

import html
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTLINE = HERE / "slide_outline.md"
OUT = HERE / "slides.html"


def inline_md(text: str) -> str:
    """Convert inline markdown (bold, italic, images) to HTML, escaping the rest.

    Order matters: images are extracted first (they contain characters that the
    emphasis rules would mangle), then bold, then italic, on escaped text.
    """
    # Pull images out as placeholders so escaping/emphasis doesn't touch them.
    images = []

    def stash_image(m):
        alt, src = m.group(1), m.group(2)
        images.append((alt, src))
        return f"\x00IMG{len(images) - 1}\x00"

    text = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", stash_image, text)

    text = html.escape(text)

    # Bold (**...**) before italic (*...*) so the double-star wins.
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)

    # Reference marks: a standalone bracketed number [N] becomes a superscript.
    # (Not followed by "(" so markdown links are left alone.)
    text = re.sub(r"\[(\d+)\](?!\()", r"<sup>[\1]</sup>", text)

    # Restore images as <img> tags.
    def restore_image(m):
        alt, src = images[int(m.group(1))]
        return f'<img src="{html.escape(src)}" alt="{html.escape(alt)}">'

    text = re.sub(r"\x00IMG(\d+)\x00", restore_image, text)
    return text


def render_table(lines: list[str]) -> str:
    """Render a GitHub-style pipe table (header, separator row, body) to HTML."""
    rows = [ln.strip().strip("|").split("|") for ln in lines]
    header = [c.strip() for c in rows[0]]
    body = [[c.strip() for c in r] for r in rows[2:]]  # skip the |---| separator
    out = ["<table>", "<thead><tr>"]
    out += [f"<th>{inline_md(c)}</th>" for c in header]
    out.append("</tr></thead><tbody>")
    for r in body:
        out.append("<tr>" + "".join(f"<td>{inline_md(c)}</td>" for c in r) + "</tr>")
    out.append("</tbody></table>")
    return "".join(out)


def md_block_to_html(block: str) -> str:
    """Convert one slide's markdown block into HTML, handling the constructs the
    outline actually uses: h1/h2, bullet lists with one level of nesting,
    pipe tables, images, and italic/bold caption/kicker lines.
    """
    lines = block.split("\n")
    out = []
    footnotes = []  # lines beginning with "^ " render in a bottom footer
    i = 0
    list_stack = 0  # 0 = not in a list, 1 = top level open, 2 = nested open

    def close_lists(to_level=0):
        nonlocal list_stack
        while list_stack > to_level:
            out.append("</ul>")
            list_stack -= 1

    while i < len(lines):
        raw = lines[i]
        line = raw.rstrip()

        if not line.strip():
            close_lists(0)
            i += 1
            continue

        # Footnote: a line starting with "^ ". Collected for the bottom footer.
        # The leading [N] label stays at the baseline (not superscripted); only
        # inline reference marks in the body are superscripted.
        if line.lstrip().startswith("^ "):
            close_lists(0)
            note = line.lstrip()[2:].strip()
            m_lbl = re.match(r"^(\[\d+\])\s*(.*)$", note)
            if m_lbl:
                footnotes.append(
                    f'<span class="fn-label">{html.escape(m_lbl.group(1))}</span> '
                    + inline_md(m_lbl.group(2))
                )
            else:
                footnotes.append(inline_md(note))
            i += 1
            continue

        # Table: a run of lines that all contain a pipe.
        if line.lstrip().startswith("|"):
            close_lists(0)
            tbl = []
            while i < len(lines) and lines[i].lstrip().startswith("|"):
                tbl.append(lines[i])
                i += 1
            out.append(render_table(tbl))
            continue

        # Headings.
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            close_lists(0)
            level = len(m.group(1))
            out.append(f"<h{level}>{inline_md(m.group(2))}</h{level}>")
            i += 1
            continue

        # List items, with one level of nesting (two-space indent).
        m = re.match(r"^(\s*)-\s+(.*)$", line)
        if m:
            indent = len(m.group(1))
            target = 2 if indent >= 2 else 1
            while list_stack < target:
                out.append("<ul>")
                list_stack += 1
            close_lists(target)
            out.append(f"<li>{inline_md(m.group(2))}</li>")
            i += 1
            continue

        # Anything else: a paragraph (kickers, captions, author line).
        close_lists(0)
        out.append(f"<p>{inline_md(line.strip())}</p>")
        i += 1

    close_lists(0)
    if footnotes:
        notes = "<br>".join(footnotes)
        out.append(f'<footer class="footnotes">{notes}</footer>')
    return "\n".join(out)


def main():
    text = OUTLINE.read_text(encoding="utf-8")

    # Drop the file's leading H1 + subtitle (lines 1-2): they are an outline
    # header, not a slide. Everything from the first slide onward is split on
    # a horizontal rule (--- on its own line).
    parts = re.split(r"^\s*---\s*$", text, flags=re.M)
    # The first part contains the outline header before the first ---; skip it.
    slide_blocks = [p.strip() for p in parts[1:] if p.strip()]

    # The first slide is the title slide (centered); the rest are left-aligned.
    section_html = []
    for idx, b in enumerate(slide_blocks):
        cls = ' class="title-slide"' if idx == 0 else ""
        section_html.append(f'      <section{cls}>\n{md_block_to_html(b)}\n      </section>')
    sections = "\n".join(section_html)

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Examining the Public Record</title>
  <link rel="stylesheet" href="reveal/reveal.css">
  <link rel="stylesheet" href="reveal/white.css" id="theme">
  <style>
    .reveal {{ font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; font-size: 30px; }}
    .reveal h1, .reveal h2 {{ color: #1a3a5c; text-transform: none; }}
    .reveal h2 {{ font-size: 1.3em; }}
    .reveal h1 {{ font-size: 1.7em; }}
    .reveal p > em:only-child {{ color: #555; }}
    .reveal li {{ margin: 0.25em 0; line-height: 1.3; }}
    /* Left-align all slide content by default; center only the title slide. */
    .reveal .slides section {{ text-align: left; }}
    .reveal .slides section.title-slide {{ text-align: center; }}
    /* Title slide: push the author/class/date block down, away from the title.
       The first two <p> are the title/subtitle; the 3rd <p> begins the author
       block, so give it a large top margin. */
    .reveal .slides section.title-slide p:nth-of-type(3) {{ margin-top: 2.5em; }}
    .reveal .slides section.title-slide p:nth-of-type(n+3) {{ font-size: 0.8em; color: #555; line-height: 1.2; margin-top: 0; margin-bottom: 0.15em; }}
    /* Keep the top gap before the author block, but tight spacing within it. */
    .reveal .slides section.title-slide p:nth-of-type(3) {{ margin-top: 2.5em; }}
    .reveal section img {{ max-height: 46vh; width: auto; border: none; box-shadow: none; margin: 6px auto; display: block; }}
    .reveal table {{ font-size: 0.78em; margin: 0 auto; }}
    .reveal table th {{ background: #1a3a5c; color: #fff; }}
    .reveal .slide-number {{ font-size: 0.6em; }}
    /* Footnotes: small, gray, separated from content by a rule. Rendered in
       normal flow (not absolutely positioned) so reveal.js layout is untouched. */
    .reveal .footnotes {{
      display: block; margin-top: 1.2em;
      font-size: 0.45em; color: #777; line-height: 1.3;
      border-top: 1px solid #ddd; padding-top: 0.4em; text-align: left;
    }}
  </style>
</head>
<body>
  <div class="reveal">
    <div class="slides">
{sections}
    </div>
  </div>
  <script src="reveal/reveal.js"></script>
  <script>
    Reveal.initialize({{
      hash: true,
      controls: false,       // no on-screen arrows; advance by mouse click
      slideNumber: 'c/t',
      transition: 'fade',
      width: 1280, height: 720,
    }});
    // Click to advance: left 15% goes back, the rest goes forward.
    document.addEventListener('click', function (e) {{
      if (e.target.closest('a') || e.target.closest('.controls')) return;
      if (e.clientX < window.innerWidth * 0.15) Reveal.left();
      else Reveal.right();
    }});
  </script>
</body>
</html>
"""
    OUT.write_text(page, encoding="utf-8")
    print(f"Wrote {OUT} with {len(slide_blocks)} slides.")


if __name__ == "__main__":
    main()
